# Generated by Django 2.2 on 2019-04-22 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2019, 4, 22, 16, 46, 49, 75393))),
            ],
        ),
    ]
