# Generated by Django 2.2 on 2019-04-30 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0004_auto_20190429_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 11, 56, 4, 561112)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
