# Generated by Django 2.2 on 2019-04-30 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0005_auto_20190430_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 12, 27, 30, 283907)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.EmailField(blank=True, max_length=2205, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
